services:
  nginx:
    volumes:
    - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    
  web-admin:
    build:
      dockerfile: apps/web-admin/Dockerfile.dev
    command: pnpm --filter web-admin dev
    env_file:
      - path: env/web-admin/.env
        required: true
      - path: env/web-admin/.env.development.local
        required: true
    volumes:
      - .:/app
  web-tenant:
    build:
      dockerfile: apps/web-tenant/Dockerfile.dev
    command: pnpm --filter web-tenant dev
    env_file:
      - path: env/web-tenant/.env
        required: true
      - path: env/web-tenant/.env.development.local
        required: true
    volumes:
      - .:/app

  api:
    build:
      dockerfile: apps/api/Dockerfile.dev
    command: pnpm --filter api dev
    env_file:
      - path: env/api/.env
        required: true
      - path: env/api/.env.development.local
        required: true
      - path: env/database/.env
        required: true
      - path: env/database/.env.development.local
        required: true
    volumes:
      - .:/app

  db-init:
    build:
      dockerfile: packages/database/docker/Dockerfile.init
    command: pnpm --filter @workspace/database db:init
    env_file:
      - path: env/db-init/.env
        required: true
      - path: env/database/.env
        required: true
      - path: env/database/.env.development.local
        required: true
    volumes:
      - .:/app

  db:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - path: env/database/.env
        required: true
      - path: env/database/.env.development.local
        required: true