services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "${HOST_NGINX}:${PORT_NGINX}"
    depends_on:
      - web-admin
      - web-tenant
      - api
  web-admin:
    build:
      context: .
      args:
        APP: web-admin
    ports:
      - "${PORT_ADMIN}"
    restart: unless-stopped
    depends_on:
      - api
  web-tenant:
    build:
      context: .
      args:
        APP: web-tenant
    ports:
      - "${PORT_TENANT}"
    restart: unless-stopped
    depends_on:
      - api
  api:
    build:
      context: .
      args:
        APP: api
    ports:
      - "${PORT_API}"
    restart: unless-stopped
    depends_on:
      db-init:
        condition: service_completed_successfully
  db-init:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: boilerplate-db
    environment:
    - DB_USERNAME=${DB_USERNAME:-admin}
    - DB_NAME=${DB_NAME:-db_dev}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
