services:
  nginx:
    volumes:
    - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    
  web-admin:
    build:
      dockerfile: apps/web-admin/Dockerfile
    command: node server.js
    env_file:
      - path: env/web-admin/.env
        required: true
      - path: env/web-admin/.env.production.local
        required: true
    volumes: []

  web-tenant:
    build:
      dockerfile: apps/web-tenant/Dockerfile
    command: node server.js
    env_file:
      - path: env/web-tenant/.env
        required: true
      - path: env/web-tenant/.env.production.local
        required: true
    volumes: []

  api:
    build:
      dockerfile: apps/api/Dockerfile
    command: node dist/main
    env_file:
      - path: env/api/.env
        required: true
      - path: env/api/.env.production.local
        required: true
      - path: env/database/.env
        required: true
      - path: env/database/.env.production.local
        required: true
    volumes: []
    
  db:
    env_file:
      - path: env/database/.env
        required: true
      - path: env/database/.env.production.local
        required: true
    volumes:
      - db-data-prod:/var/lib/postgresql/data

volumes:
  db-data-prod: