services:
  nginx:
    volumes:
    - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    
  web-admin:
    build:
      dockerfile: apps/web-admin/Dockerfile
    command: node server.js
    env_file:
      - env/web-admin/.env
      - env/web-admin/.env.production.local
    volumes: []

  web-tenant:
    build:
      dockerfile: apps/web-tenant/Dockerfile
    command: node server.js
    env_file:
      - env/web-tenant/.env
      - env/web-tenant/.env.production.local
    volumes: []

  api:
    build:
      dockerfile: apps/api/Dockerfile
    command: node dist/main
    env_file:
      - env/api/.env
      - env/api/.env.production.local
      - env/database/.env
      - env/database/.env.production.local
    volumes: []

  db:
    env_file:
      - env/database/.env
      - env/database/.env.production.local
    volumes:
      - db-data-prod:/var/lib/postgresql/data

volumes:
  db-data-prod: