services:
  nginx:
    volumes:
    - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    
  web-admin:
    build:
      dockerfile: apps/web-admin/Dockerfile.dev
    command: pnpm --filter web-admin dev
    env_file:
      - env/web-admin/.env
      - env/web-admin/.env.development.local
    volumes:
      - .:/app
  web-tenant:
    build:
      dockerfile: apps/web-tenant/Dockerfile.dev
    command: pnpm --filter web-tenant dev
    env_file:
      - env/web-tenant/.env
      - env/web-tenant/.env.development.local
    volumes:
      - .:/app
  api:
    build:
      dockerfile: apps/api/Dockerfile.dev
    command: pnpm --filter api dev
    env_file:
      - env/api/.env
      - env/api/.env.development.local
      - env/database/.env
      - env/database/.env.development.local
    volumes:
      - .:/app

  db:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - env/database/.env
      - env/database/.env.development.local