FROM node:20-alpine

RUN apk update && apk add --no-cache libc6-compat
RUN npm install -g pnpm@10.4.1 turbo@2.1.3

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3001
CMD ["pnpm", "dev:web-tenant"]