FROM node:20-alpine

RUN apk update && apk add --no-cache libc6-compat
RUN npm install -g pnpm@10.4.1 turbo@2.1.3

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Build the target app and all of its dependencies. Turborepo will
# determine the correct build order.
RUN pnpm --filter @workspace/web-admin... build

EXPOSE 3000

CMD ["pnpm", "dev:web-admin"]
